name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements
      run: |
        set -ex
        python -VV
        python -m site
        python -m pip install coverage Pygments==2.15.1
    - name: Run package build checks
      run: python setup.py test
    - name: Run package coverage checks
      run: |
        coverage run --source=plerr.cli -m \
        unittest -v plerr/tests/test_cli_module.py && \
        coverage report && coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
          file: ./coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
